apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: wu66o8ix1-java-quarkus
  janus-idp.io/tekton: wu66o8ix1-java-quarkus
  backstage.io/kubernetes-id: wu66o8ix1-java-quarkus
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: wu66o8ix1-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
